.TH miral\-shell "1" "April 2020" "1.8.0" "Mir Display Server Demo Application"

.SH NAME
mir\-shell \- Mir Display Server shell launch script

.SH SYNOPSIS
\fB\,mir\-shell\/\fR
\fI[\,options\/] [\,shell options\/]\fR

.SH DESCRIPTION
\fBmir\-shell\fR launches a Mir Display Server shell.


.SH OPTIONS

.TP
\fB\-terminal\fR \fI<terminal>\fR
Use \fI<terminal>\fR instead of 'x-terminal-emulator'.
.TP
\fB\-bindir\fR \fI<bindir>\fR
Path to the miral-shell executable [/usr/bin].

.SH SHELL OPTIONS

.PP
See miral-shell(1) for further Mir shell options.

.SH SEE ALSO
mir-kiosk(1), miral-shell(1)

.SH AUTHOR
The Mir Display Server has been written by the Mir Server Team at Canonical
Ltd.
.PP
This man page has been written for the Debian project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de> and may be re-used by others.
