.TH mir_demo_client_fingerpaint "1" "April 2020" "1.8.0" "Mir Client Demo Application"

.SH NAME
mir_demo_client_fingerpaint \- Mir Client Demo Application

.SH SYNOPSIS
.B mir_demo_client_fingerpaint
[\fI\,<options>\/\fR]

.SH DESCRIPTION
Launch a Mir client demo (fingerpaint demo).

.SH OPTIONS
This application accepts the following options:
.TP
\fB\-h\fR
Show this help text and exit.
.TP
\fB\-m\fR \fI<mir\-server\-socket\-file\-path>\fR
Full path to the Mir server socket file.
.TP
\fB\-r\fR \fI<radius>\fR
Force paint brush radius.
.TP
\fB\-w\fR
Wait for vblank (don't drop frames).
.TP
\fB\-\-\fR
Ignore further arguments.

.SH AUTHOR
The Mir Display Server has been written by the Mir Server Team at Canonical
Ltd.
.PP
This man page has been written for the Debian project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de> and may be re-used by others.
