.TH mir_demo_client_flicker "1" "April 2020" "1.8.0" "Mir Client Demo Application"

.SH NAME
mir_demo_client_flicker \- Mir Client Demo Application

.SH SYNOPSIS
.B mir_demo_client_flicker
[\fI\,<options>\/\fR]

.SH DESCRIPTION
Launch a Mir client demo (flicker demo).

.SH OPTIONS
This application accepts the following options:
.TP
\fB\-m\fR \fI<mir\-server\-socket\-file\-path>\fR
Full path to the Mir server socket file.
.TP
\fB\-h\fR
Show this help text and exit.
.TP
\fB\-n\fR
Don't sync to vblank
.TP
\fB\-q\fR
Quiet mode (no messages output)

.SH AUTHOR
The Mir Display Server has been written by the Mir Server Team at Canonical
Ltd.
.PP
This man page has been written for the Debian project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de> and may be re-used by others.
