.TH miral\-terminal "1" "April 2020" "1.8.0" "Mir Display Server Demo Application"

.SH NAME
miral\-terminal \- Terminal wrapper for Mir Display Server

.SH SYNOPSIS
\fB\,miral\-terminal\/\fR
\fI[\,options\/]\fR

.SH DESCRIPTION
\fBmiral\-terminal\fR launches a terminal window in the Mir Display Server shell.
.PP
It is a script that wraps around the first found terminal application and
launches it in a separate process.

.SH OPTIONS
This script forwards all command line options to the evoked terminal application.

.SH SEE ALSO
mir-shell(1)

.SH AUTHOR
The Mir Display Server has been written by the Mir Server Team at Canonical
Ltd.
.PP
This man page has been written for the Debian project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de> and may be re-used by others.
