.TH mirin "1" "April 2020" "1.8.0" "Mir Display Server Tool"

.SH NAME
mirin \- FIXME: FUNCTIONALITY UNKNOWN

.SH SYNOPSIS
.B mirin
[\fI\,<socket-file>\/\fR] [\fI\,--\/\fR]

.SH DESCRIPTION
FIXME: DESCRIPTION UNKNOWN

.SH OPTIONS
.TP
\fB\-\-\fR
Ignore the rest of the command line.

.SH SEE ALSO
mirout(1)

.SH AUTHOR
The Mir Display Server has been written by the Mir Server Team at Canonical
Ltd.
.PP
This man page has been written for the Debian project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de> and may be re-used by others.
